[package]
name = "knightime_engine"
version = "0.1.0"
authors = ["niconico <joulin.nicolas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
knightime = { git = "https://github.com/niconicoj/Knightime" }
